import { Clue, CaseDeduction } from '../types/game';

export const INITIAL_CLUES: Clue[] = [
  {
    id: 'clue_newspaper',
    title: 'Пожелтевшая газета (1989 г.)',
    category: 'document',
    description: 'Первая полоса 35-летней давности из газеты «Вестник Шепчущих Сосен».',
    locationFound: 'town',
    details: '«ПЯТЕРО ЖИТЕЛЕЙ ИСЧЕЗЛИ ЗА ОДНУ НОЧЬ: Шеф полиции Дэниел Вэнс заверяет граждан, что поисковые отряды прочёсывают Блэквудский хребет. Введён комендантский час. Жители сообщают о странном низком гуле и вибрациях под полами подвалов перед исчезновениями».',
    discovered: false,
    icon: 'newspaper',
    connections: ['clue_necklace', 'clue_daniel_badge'],
  },
  {
    id: 'clue_necklace',
    title: 'Серебряный медальон пропавшей девочки',
    category: 'artifact',
    description: 'С гравировкой инициалов «Э.В.». Найден на крыльце заброшенного дома.',
    locationFound: 'town',
    details: 'Внутри медальона — крошечный портрет юной Эвелин Вэнс (дочери Дэниела). На застёжке виден налёт, который мерцает фиолетовым светом под УФ-лучом фонаря.',
    discovered: false,
    icon: 'gem',
    connections: ['clue_newspaper', 'clue_torn_diary'],
  },
  {
    id: 'clue_torn_diary',
    title: 'Вырванная страница дневника',
    category: 'document',
    description: 'Истлевший рукописный лист, найденный под половицами заброшенного дома.',
    locationFound: 'house',
    details: '«14 октября: Отец уверяет, что шахту закрыли из-за обвалов, но каждую полночь я слышу, как клеть лифта спускается вниз. Огни на церковной колокольне горят без огня. Код к терминалу отца в подвале спрятан в частотах: 4-7-2-9».',
    discovered: false,
    icon: 'book-open',
    contradictionWith: 'clue_daniel_statement',
    connections: ['clue_necklace', 'clue_audio_tape'],
  },
  {
    id: 'clue_broken_flashlight',
    title: 'Разбитый промышленный фонарь',
    category: 'artifact',
    description: 'Помятый шахтёрский фонарь, найденный у тропы в глухом лесу.',
    locationFound: 'forest',
    details: 'На корпусе глубокие следы когтей и копоть, не похожая на следы обычного огня. Клеймо производителя гласит: «БУРОВАЯ КОРПОРАЦИЯ БЛЭКВУД — СЕКТОР 4».',
    discovered: false,
    icon: 'flashlight',
    connections: ['clue_strange_symbol', 'clue_mine_map'],
  },
  {
    id: 'clue_strange_symbol',
    title: 'Вырезанный оккультный знак',
    category: 'artifact',
    description: 'Перевёрнутый глаз, заключённый в тройную спираль, высеченный на коре древней сосны.',
    locationFound: 'forest',
    details: 'Символ в точности повторяет гравировку на алтаре в подземелье церкви и клейма на военных герметичных ящиках.',
    discovered: false,
    icon: 'eye',
    connections: ['clue_broken_flashlight', 'clue_church_record'],
  },
  {
    id: 'clue_rusty_key',
    title: 'Тяжёлый латунный ключ №13',
    category: 'artifact',
    description: 'Старинный ключ с патиной и насечками. На пластине выбито: «КРИПТА №13».',
    locationFound: 'forest',
    details: 'Подходит к массивному железному замку, запирающему решётку склепа под кладбищем старой церкви.',
    discovered: false,
    icon: 'key',
    connections: ['clue_church_record'],
  },
  {
    id: 'clue_mine_map',
    title: 'План-схема шахты сектора 4',
    category: 'document',
    description: 'Инженерный чертёж заброшенных медных выработок.',
    locationFound: 'mine',
    details: 'На третьем горизонте стоит красный штамп: «ШТОЛЬНЯ ЗАПЕЧАТАНА ФЕДЕРАЛЬНЫМ ПРИКАЗОМ 1982 ГОДА — ОБНАРУЖЕНА РЕЗОНАНСНАЯ ПОЛОСТЬ». Нарисованная от руки стрелка ведёт за обрушенную каменную стену к «БУНКЕРНОМУ ШЛЮЗУ».',
    discovered: false,
    icon: 'map',
    connections: ['clue_broken_flashlight', 'clue_lab_note'],
  },
  {
    id: 'clue_audio_tape',
    title: 'Микрокассета: «Запись 084»',
    category: 'recording',
    description: 'Магнитная аудиоплёнка с выцветшей надписью красным маркером.',
    locationFound: 'mine',
    details: 'Сквозь помехи слышно прерывистое дыхание: «Если вы слышите это, значит противовзрывные двери не удержали... Это был не обвал. Частота, которую они закачивали в породу... она начала эхом отзываться их голосами. Аварийный код шлюза изолятора: 4-7-2-9».',
    discovered: false,
    icon: 'disc',
    connections: ['clue_torn_diary', 'clue_security_recording'],
  },
  {
    id: 'clue_church_record',
    title: 'Церковная книга погребений (1975–1990)',
    category: 'document',
    description: 'Приходской гроссбух в кожаном переплёте из церкви Святого Иуды.',
    locationFound: 'church',
    details: 'Начиная с ноября 1989 года все имена зачёркнуты густыми чернилами, а почерком Марты выведено слово «ПЕРЕМЕЩЕНЫ». На полях пометка: порядок камней алтаря — СОЛНЦЕ, ЛУНА, ЧЕРЕП, ЗМЕЯ.',
    discovered: false,
    icon: 'scroll',
    contradictionWith: 'clue_martha_testimony',
    connections: ['clue_strange_symbol', 'clue_old_photo'],
  },
  {
    id: 'clue_old_photo',
    title: 'Фото городского совета (1984 г.)',
    category: 'photograph',
    description: 'Чёрно-белый групповой снимок основателей города и церковных старейшин.',
    locationFound: 'church',
    details: 'В заднем ряду стоят Марта, шеф Дэниел и лаборанты в защитных комбинезонах. За ними сквозь матовое стекло виден высокий тёмный силуэт с горящими белыми глазами.',
    discovered: false,
    icon: 'camera',
    connections: ['clue_church_record', 'clue_lab_note'],
  },
  {
    id: 'clue_daniel_badge',
    title: 'Окровавленный жетон помощника шерифа',
    category: 'artifact',
    description: 'Принадлежал помощнику Хейзу — бывшему напарнику Дэниела.',
    locationFound: 'house',
    details: 'Помят колоссальной сдавливающей силой. Группа крови не совпадает ни с одной стандартной группой человека из архивов участка.',
    discovered: false,
    icon: 'shield',
    connections: ['clue_newspaper', 'clue_security_recording'],
  },
  {
    id: 'clue_lab_note',
    title: 'Памятка доктора Стерлинга',
    category: 'document',
    description: 'Секретная служебная записка из подземного уровня 3.',
    locationFound: 'lab',
    details: '«Проект "Глубокое Эхо" подтвердил: организм под коренной породой не воспринимает дневной свет, но охотится на оптико-акустические частоты в ночное время. Подопытные не погибли; они были ассимилированы в теневой резонанс».',
    discovered: false,
    icon: 'file-text',
    connections: ['clue_mine_map', 'clue_security_recording'],
  },
  {
    id: 'clue_security_recording',
    title: 'Бобина видеонаблюдения «Чёрный ящик»',
    category: 'recording',
    description: 'Защищённая бобина из изолятора секции B.',
    locationFound: 'lab',
    details: 'Метка времени: 03:14 ночи. Камера фиксирует Марту и Дэниела у пульта. При сирене тень скользит по стеклу, и Дэниел отключает лифт, запирая группу исследователей внизу ради спасения города наверху.',
    discovered: false,
    icon: 'video',
    contradictionWith: 'clue_daniel_statement',
    connections: ['clue_lab_note', 'clue_audio_tape'],
  },
  {
    id: 'clue_polaroid_anomaly',
    title: 'Спектральный снимок Polaroid',
    category: 'photograph',
    description: 'Проявленный снимок, сделанный детективной камерой.',
    locationFound: 'town',
    details: 'На снимке проявилась светящаяся призрачная надпись на церковной колокольне: «ИСТОЧНИК ВСЁ ЕЩЁ ПУЛЬСИРУЕТ ПОД БУРОМ. ПЕРЕКЛЮЧИТЕ ТРИ РЕЛЕ, ЧТОБЫ ОБЕСТОЧИТЬ ЯДРО».',
    discovered: false,
    icon: 'image',
    connections: ['clue_lab_note', 'clue_security_recording'],
  }
];

export const INITIAL_DEDUCTIONS: CaseDeduction[] = [
  {
    id: 'deduction_1',
    prompt: 'Что послужило причиной внезапного исчезновения пяти жителей?',
    requiredClues: ['clue_newspaper', 'clue_necklace', 'clue_torn_diary'],
    solved: false,
    conclusion: 'Жертвы не были атакованы дикими зверями; их приманило к шахтному подъёмнику после того, как они услышали подземные вибрации.',
    unlockedChapter: 2,
  },
  {
    id: 'deduction_2',
    prompt: 'Кто действовал в тёмном лесу и заброшенных штольнях?',
    requiredClues: ['clue_broken_flashlight', 'clue_strange_symbol', 'clue_mine_map'],
    solved: false,
    conclusion: 'Буровая корпорация Блэквуд вела тайные раскопки в глубоких пластах, вскрыв древнюю подземную резонансную полость.',
    unlockedChapter: 3,
  },
  {
    id: 'deduction_3',
    prompt: 'Почему церковные книги погребений были сфальсифицированы?',
    requiredClues: ['clue_church_record', 'clue_old_photo', 'clue_rusty_key'],
    solved: false,
    conclusion: 'Основатели города, включая Марту и Дэниела, заключили пакт о сокрытии комплекса под церковной криптой после прорыва изоляции.',
    unlockedChapter: 4,
  },
  {
    id: 'deduction_4',
    prompt: 'В чём заключалась истинная суть проекта «Глубокое Эхо» в лаборатории?',
    requiredClues: ['clue_audio_tape', 'clue_lab_note', 'clue_security_recording'],
    solved: false,
    conclusion: 'Организм — это теневое сознание, разбуженное акустическим бурением, выходящее наружу только ночью через искривления света.',
    unlockedChapter: 6,
  }
];

export const CHAPTER_NAMES = [
  'ГЛАВА 1 — ОПУСТЕВШИЙ ГОРОД',
  'ГЛАВА 2 — ТЁМНЫЙ ЛЕС',
  'ГЛАВА 3 — ЗАБРОШЕННАЯ ШАХТА',
  'ГЛАВА 4 — ТАИНСТВЕННАЯ ЦЕРКОВЬ',
  'ГЛАВА 5 — ПОДЗЕМЕЛЬЕ ГОРОДА',
  'ГЛАВА 6 — ОБНАЖЁННАЯ ИСТИНА'
];
